version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: ecowas_pg
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data:rw
    env_file: '.env'
    networks:
      - ecowas_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:5050"
    env_file: '.env'
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - postgres:postgres
    networks:
      - ecowas_network
    depends_on:
      - postgres

volumes:
  data:
  pgadmin:
  
networks:
  ecowas_network:
    driver: bridge